### ISSUE TITLE
How to generate single source file from it?

### ISSUE THREAD

**Issue by ishandutta2007** [bayashi-cl/byslib#2]
You have expander for python.
What do you use for c++?

**Comment by bayashi-cl** [comment]
No, it expands `#include "..."` mechanically.

**Comment by bayashi-cl** [comment]
That is because online-judge-tools is developed for competitive programming, and I thought I could manage libraries, download samples, and submit solutions all in one place with this toolchain. Note that these tools are intended for small libraries for competition programming. For such applications, it is sufficient to extract the entire source file.

(Also, `gcc -E` expands STL as well as my library.)

"amalgamate" was a concept I was unaware of. Thank you for your help.

**Comment by ishandutta2007** [comment]
Why are you closing it ? It is solved ?


There are many  "amalgamation"("expander" is wrong term) tools on github . You should take inspiration from these and customize this.


- https://stackoverflow.com/questions/2719311/tool-to-create-an-amalgamation-combine-all-source-files-of-a-library-into-one-fo
- https://stackoverflow.com/questions/50887018/cmake-generate-single-header-file

**Comment by bayashi-cl** [comment]
1. about "expander"

    The name comes from the `ac-library`'s expander.py. Among the Japanese competitive programming community, this name is often used for programs that make libraries to be able to submitted to online judges.

    * https://github.com/atcoder/ac-library/blob/master/expander.py
    * https://github.com/zer0-star/Nim-ACL/blob/master/expander.py
    * https://github.com/rust-lang-ja/ac-library-rs/blob/master/expand.py

1. the objective of "expander"

    The objective of `oj-bundle` is described here: <https://github.com/online-judge-tools/verification-helper/blob/master/DESIGN.md>. My tool has much the same purpose.

    > For small libraries `Ctrl+C + Ctrl+V` is faster.

    My library currently consists of dozens of files, some of which have dependencies. It is more efficient and accurate to generate code than to copy-paste with that dependency in mind.

    > ... remember each function name, their signature, boundary cases ...
    
    With docstrings, type hints, etc., the effort is sufficiently reduced to benefit from the IDE. The `online-judge-tools/verification-helper` can also list the modules in the library. Also, in most cases the function names are the same as the algorithm names.

1. about the code-coverage idea

    Honestly, I don't see how that idea would work, because to estimate code-coverage accurately you would need to make as many test cases as system cases. Creating such test cases for every problem during a contest is a waste of time, and I don't want to sacrifice accuracy for a shorter amount of code.
